/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DataSetRouteImport } from './routes/$dataSet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataSetIndexRouteImport } from './routes/$dataSet/index'
import { Route as DataSetSessionRouteImport } from './routes/$dataSet/session'
import { Route as DataSetBrowseRouteImport } from './routes/$dataSet/browse'

const DataSetRoute = DataSetRouteImport.update({
  id: '/$dataSet',
  path: '/$dataSet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSetIndexRoute = DataSetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataSetRoute,
} as any)
const DataSetSessionRoute = DataSetSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => DataSetRoute,
} as any)
const DataSetBrowseRoute = DataSetBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => DataSetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$dataSet': typeof DataSetRouteWithChildren
  '/$dataSet/browse': typeof DataSetBrowseRoute
  '/$dataSet/session': typeof DataSetSessionRoute
  '/$dataSet/': typeof DataSetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$dataSet/browse': typeof DataSetBrowseRoute
  '/$dataSet/session': typeof DataSetSessionRoute
  '/$dataSet': typeof DataSetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$dataSet': typeof DataSetRouteWithChildren
  '/$dataSet/browse': typeof DataSetBrowseRoute
  '/$dataSet/session': typeof DataSetSessionRoute
  '/$dataSet/': typeof DataSetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$dataSet'
    | '/$dataSet/browse'
    | '/$dataSet/session'
    | '/$dataSet/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$dataSet/browse' | '/$dataSet/session' | '/$dataSet'
  id:
    | '__root__'
    | '/'
    | '/$dataSet'
    | '/$dataSet/browse'
    | '/$dataSet/session'
    | '/$dataSet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataSetRoute: typeof DataSetRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$dataSet': {
      id: '/$dataSet'
      path: '/$dataSet'
      fullPath: '/$dataSet'
      preLoaderRoute: typeof DataSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$dataSet/': {
      id: '/$dataSet/'
      path: '/'
      fullPath: '/$dataSet/'
      preLoaderRoute: typeof DataSetIndexRouteImport
      parentRoute: typeof DataSetRoute
    }
    '/$dataSet/session': {
      id: '/$dataSet/session'
      path: '/session'
      fullPath: '/$dataSet/session'
      preLoaderRoute: typeof DataSetSessionRouteImport
      parentRoute: typeof DataSetRoute
    }
    '/$dataSet/browse': {
      id: '/$dataSet/browse'
      path: '/browse'
      fullPath: '/$dataSet/browse'
      preLoaderRoute: typeof DataSetBrowseRouteImport
      parentRoute: typeof DataSetRoute
    }
  }
}

interface DataSetRouteChildren {
  DataSetBrowseRoute: typeof DataSetBrowseRoute
  DataSetSessionRoute: typeof DataSetSessionRoute
  DataSetIndexRoute: typeof DataSetIndexRoute
}

const DataSetRouteChildren: DataSetRouteChildren = {
  DataSetBrowseRoute: DataSetBrowseRoute,
  DataSetSessionRoute: DataSetSessionRoute,
  DataSetIndexRoute: DataSetIndexRoute,
}

const DataSetRouteWithChildren =
  DataSetRoute._addFileChildren(DataSetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataSetRoute: DataSetRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
